### ISSUE TITLE
고객센터 게시판 누락사항 리팩토링

### ISSUE THREAD

**Issue by psw4887** [nhn-on7/marketgg-client#107]
## Description
1. Shop 서버와의 연동간에 있어서 누락사항 Refactoring

## TODO
- [ ] 사유 선택 추가
- [ ] 상태 변경 추가
- [ ] 관리자 서비스 & 컨트롤러 추가
