### ISSUE TITLE
게시판 최종 수정 및 코드 리팩토링

### ISSUE THREAD

**Issue by psw4887** [nhn-on7/marketgg-client#113]
## Description
1. 게시판의 전체적인 통합을 위한 코드 수정
2. 어지러운 매핑 정리 및 요청/응답 객체 통일

## TODO
- [ ] 고객센터 공지사항 CRUD
- [ ] 고객센터 FAQ CRUD
- [ ] 고객센터 1:1 문의 CRUD
