### ISSUE TITLE
UI 디자인 고도화

### ISSUE THREAD

**Issue by psw4887** [nhn-on7/marketgg-client#132]
## Description
1. 현재 구현이 끝난 도메인에 한해서 UI 고도화 작업 진행

## TODO
- [x] 라벨 UI 고도화
- [x] GG Pass UI 고도화
- [x] My GG 찜 목록 UI 고도화
- [x] 고객센터 게시판 UI 고도화
