### ISSUE TITLE
구현한 도메인 별 Adapter 테스트

### ISSUE THREAD

**Issue by psw4887** [nhn-on7/marketgg-client#141]
## Description
1. Client 에서 Shop으로 연결하고 있는 Adapter 의 테스트 코드 작성 

## TODO
- [ ] CategoryAdapter Test 작성
- [ ] CommentAdapter Test 작성
- [ ] DibAdapter Test 작성
- [ ] LabelAdapter Test 작성
- [ ] GG PassAdapter Test 작성
- [ ] PostAdapter Test 작성
