### ISSUE TITLE
테스트 코드 수정

### ISSUE THREAD

**Issue by psw4887** [nhn-on7/marketgg-client#144]
## Overview

1. 테스트 코드의 명확성 및 통일성 유지

## To-do

- [x] 불필요한 테스트 코드 라인 삭제
- [x] 필요한 테스트 코드 라인 추가
- [x] Mockito -> BDD Mockito 통일
