### ISSUE TITLE
UI 작업 마무리

### ISSUE THREAD

**Issue by psw4887** [nhn-on7/marketgg-client#189]
## Description
1. 진짜 UI 작업을 마무리해보자

## TODO
- [ ] 고객센터 UI 정리
- [ ] 라벨 UI 정리
- [ ] 찜 목록 조회 UI 정리
- [ ] 상품 검색 UI 정리
