### ISSUE TITLE
카테고리 공통 코드 작성

### ISSUE THREAD

**Issue by Jungmin-Kim228** [nhn-on7/marketgg-client#21]
1. 카테고리 관리를 시작하기 앞서 공통적인 기반 코드 작성
2. 패키지 정리

## TODO
- [x] 카테고리 controller, service 작성
- [x] 카테고리 templates 의 html 파일 구성
- [x] request, response 패키지 정리

**Comment by Jungmin-Kim228** [comment]
카테고리 공통 코드 작성을 완료하였습니다.
해당 이슈는 닫고 새 이슈를 추가하겠습니다.

### 2022-07-11 이전 Done
- feature/category 브랜치에서 CRUD feature 브랜치를 각각 생성하여 제품 코드와 테스트 코드 작성 및 병합 완료

### 2022-07-12 이후 Todo
- feature/category 브랜치에서 UI 관련 브랜치를 생성하여 UI 구현
