### ISSUE TITLE
9.5 시연 피드백

### ISSUE THREAD

**Issue by Jungmin-Kim228** [nhn-on7/marketgg-client#251]
## Description
1. 시연 후 피드백 적용

## TODO
- [x] 주문 및 결제 취소 완료 후 redirect 를 주문 내역으로
- [x] 주문 취소시 환급 계좌번호 입력란 X
- [x] 관리자 주문 상세 조회 폰트 크기 수정
- [x] 카테고리 관리 통합
- [x] 주문 관리 통합
- [x] 관리자 주문 목록 조회 회원명 추가
- [x] 이 외 수정사항 있으면 수정
