### ISSUE TITLE
공통 페이지 마크업

### ISSUE THREAD

**Issue by corock** [nhn-on7/marketgg-client#26]
## To-do

- [x] `application.yml` 설정 추가

### HTML

- [x] `classpath:/templates/include/header.html` 추가
- [x] `classpath:/templates/include/gnb.html` 추가
- [x] `classpath:/templates/include/footer.html` 추가

### CSS

- [x] 커스텀 Reset CSS 추가
