### ISSUE TITLE
AdminLabelController 개선

### ISSUE THREAD

**Issue by corock** [nhn-on7/marketgg-client#39]
## To-do

- [x] 변수명 `mv` 에서 `mav` 로 수정
- [x] `setViewName` 메서드 삭제
- [x] `public` 접근 지정자 추가
