### ISSUE TITLE
[ES] Adapter Refactoring

### ISSUE THREAD

**Issue by psw4887** [nhn-on7/marketgg-client#93]
## Description
1. 여러 정렬 기준마다  다른 객체를 생성해서 요청 정보를 생성 하는 코드를 바꿔보자.

## TODO
- [ ] Generic 활용
- [ ] 불필요한 Class 제거
- [ ] 불필요한 method 제가
- [ ] Refactoring 에 따른 Test 수정
